name: 'Beta package updater'
description: 'Update the current package version with the build number'
inputs:
  build-id:
    description: 'Build ID'
    required: true
  path:
    description: 'Path of the package.json file'
    required: true
    default: 'package.json'
outputs:
  version:
    description: 'The new version ID'
runs:
  using: 'node16'
  main: 'dist/index.js'
